// Popular travel destinations with their countries
export const popularLocations = [
  // Europe
  { city: 'Paris', country: 'France', flag: '🇫🇷' },
  { city: 'London', country: 'United Kingdom', flag: '🇬🇧' },
  { city: 'Rome', country: 'Italy', flag: '🇮🇹' },
  { city: 'Barcelona', country: 'Spain', flag: '🇪🇸' },
  { city: 'Amsterdam', country: 'Netherlands', flag: '🇳🇱' },
  { city: 'Berlin', country: 'Germany', flag: '🇩🇪' },
  { city: 'Prague', country: 'Czech Republic', flag: '🇨🇿' },
  { city: 'Vienna', country: 'Austria', flag: '🇦🇹' },
  { city: 'Athens', country: 'Greece', flag: '🇬🇷' },
  { city: 'Istanbul', country: 'Turkey', flag: '🇹🇷' },
  { city: 'Lisbon', country: 'Portugal', flag: '🇵🇹' },
  { city: 'Dublin', country: 'Ireland', flag: '🇮🇪' },
  { city: 'Copenhagen', country: 'Denmark', flag: '🇩🇰' },
  { city: 'Stockholm', country: 'Sweden', flag: '🇸🇪' },
  { city: 'Oslo', country: 'Norway', flag: '🇳🇴' },
  { city: 'Reykjavik', country: 'Iceland', flag: '🇮🇸' },
  { city: 'Budapest', country: 'Hungary', flag: '🇭🇺' },
  { city: 'Warsaw', country: 'Poland', flag: '🇵🇱' },
  { city: 'Brussels', country: 'Belgium', flag: '🇧🇪' },
  { city: 'Zurich', country: 'Switzerland', flag: '🇨🇭' },
  { city: 'Munich', country: 'Germany', flag: '🇩🇪' },
  { city: 'Florence', country: 'Italy', flag: '🇮🇹' },
  { city: 'Venice', country: 'Italy', flag: '🇮🇹' },
  { city: 'Milan', country: 'Italy', flag: '🇮🇹' },
  { city: 'Madrid', country: 'Spain', flag: '🇪🇸' },
  { city: 'Seville', country: 'Spain', flag: '🇪🇸' },
  { city: 'Edinburgh', country: 'United Kingdom', flag: '🇬🇧' },
  { city: 'Porto', country: 'Portugal', flag: '🇵🇹' },

  // Asia
  { city: 'Tokyo', country: 'Japan', flag: '🇯🇵' },
  { city: 'Bangkok', country: 'Thailand', flag: '🇹🇭' },
  { city: 'Singapore', country: 'Singapore', flag: '🇸🇬' },
  { city: 'Hong Kong', country: 'China', flag: '🇭🇰' },
  { city: 'Seoul', country: 'South Korea', flag: '🇰🇷' },
  { city: 'Dubai', country: 'UAE', flag: '🇦🇪' },
  { city: 'Bali', country: 'Indonesia', flag: '🇮🇩' },
  { city: 'Kyoto', country: 'Japan', flag: '🇯🇵' },
  { city: 'Shanghai', country: 'China', flag: '🇨🇳' },
  { city: 'Beijing', country: 'China', flag: '🇨🇳' },
  { city: 'Phuket', country: 'Thailand', flag: '🇹🇭' },
  { city: 'Hanoi', country: 'Vietnam', flag: '🇻🇳' },
  { city: 'Ho Chi Minh City', country: 'Vietnam', flag: '🇻🇳' },
  { city: 'Kuala Lumpur', country: 'Malaysia', flag: '🇲🇾' },
  { city: 'Mumbai', country: 'India', flag: '🇮🇳' },
  { city: 'Delhi', country: 'India', flag: '🇮🇳' },
  { city: 'Tel Aviv', country: 'Israel', flag: '🇮🇱' },
  { city: 'Jerusalem', country: 'Israel', flag: '🇮🇱' },
  { city: 'Manila', country: 'Philippines', flag: '🇵🇭' },
  { city: 'Osaka', country: 'Japan', flag: '🇯🇵' },

  // Americas
  { city: 'New York', country: 'United States', flag: '🇺🇸' },
  { city: 'Los Angeles', country: 'United States', flag: '🇺🇸' },
  { city: 'San Francisco', country: 'United States', flag: '🇺🇸' },
  { city: 'Las Vegas', country: 'United States', flag: '🇺🇸' },
  { city: 'Miami', country: 'United States', flag: '🇺🇸' },
  { city: 'Chicago', country: 'United States', flag: '🇺🇸' },
  { city: 'Seattle', country: 'United States', flag: '🇺🇸' },
  { city: 'Boston', country: 'United States', flag: '🇺🇸' },
  { city: 'Toronto', country: 'Canada', flag: '🇨🇦' },
  { city: 'Vancouver', country: 'Canada', flag: '🇨🇦' },
  { city: 'Montreal', country: 'Canada', flag: '🇨🇦' },
  { city: 'Mexico City', country: 'Mexico', flag: '🇲🇽' },
  { city: 'Cancun', country: 'Mexico', flag: '🇲🇽' },
  { city: 'Buenos Aires', country: 'Argentina', flag: '🇦🇷' },
  { city: 'Rio de Janeiro', country: 'Brazil', flag: '🇧🇷' },
  { city: 'São Paulo', country: 'Brazil', flag: '🇧🇷' },
  { city: 'Lima', country: 'Peru', flag: '🇵🇪' },
  { city: 'Santiago', country: 'Chile', flag: '🇨🇱' },
  { city: 'Bogotá', country: 'Colombia', flag: '🇨🇴' },
  { city: 'Havana', country: 'Cuba', flag: '🇨🇺' },

  // Oceania
  { city: 'Sydney', country: 'Australia', flag: '🇦🇺' },
  { city: 'Melbourne', country: 'Australia', flag: '🇦🇺' },
  { city: 'Auckland', country: 'New Zealand', flag: '🇳🇿' },
  { city: 'Brisbane', country: 'Australia', flag: '🇦🇺' },
  { city: 'Perth', country: 'Australia', flag: '🇦🇺' },
  { city: 'Wellington', country: 'New Zealand', flag: '🇳🇿' },

  // Africa & Middle East
  { city: 'Cairo', country: 'Egypt', flag: '🇪🇬' },
  { city: 'Marrakech', country: 'Morocco', flag: '🇲🇦' },
  { city: 'Cape Town', country: 'South Africa', flag: '🇿🇦' },
  { city: 'Nairobi', country: 'Kenya', flag: '🇰🇪' },
  { city: 'Casablanca', country: 'Morocco', flag: '🇲🇦' },
  { city: 'Johannesburg', country: 'South Africa', flag: '🇿🇦' },
  { city: 'Riyadh', country: 'Saudi Arabia', flag: '🇸🇦' },
  { city: 'Doha', country: 'Qatar', flag: '🇶🇦' },
  { city: 'Abu Dhabi', country: 'UAE', flag: '🇦🇪' }
];
